[tool.poetry]
name = "simulation"
version = "0.1.0"
description = "Simulates orbits near Lagrange Points"
authors = ["Moussa Mikhail <moussamikhail56@gmail.com>"]
license = "GPL3"
packages = [
	{ include = "simulation" }
]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
pyqtgraph = "^0.13.1"
validateddescriptor = {git = "https://github.com/Moussa-Mikhail/validated-descriptor.git", rev = "main"}
PyQt6 = "^6.4.0"
numba = "^0.56.3"
numpy = "^1.23.4"

[tool.poetry.dev-dependencies]
pylint = "^2.15.4"
flake8-comprehensions = "^3.8.0"
flake8-bugbear = "^22.3.23"
pyinstaller = "^5.5"
flake8 = "^5.0.4"
mypy = "^0.982"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

