[tool.poetry]
name = "langrangepointgui"
version = "0.1.0"
description = "Gui used to simulates orbits near Lagrange Points"
authors = ["Moussa Mikhail <moussamikhail56@gmail.com>"]
license = "GPL3"
packages = [
	{ include = "lagrangepointgui" }
]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
pyqtgraph = "^0.13.1"
PyQt6 = "^6.4.0"
numpy = "^1.23.4"
lagrangepointsimulator = {git = "https://github.com/Moussa-Mikhail/lagrange_point_orbit_simulator.git", rev = "main"}


[tool.poetry.dev-dependencies]
pylint = "^2.15.4"
flake8-comprehensions = "^3.8.0"
flake8-bugbear = "^22.3.23"
pyinstaller = "^5.5"
flake8 = "^6.0.0"
mypy = "^0.991"
black = {extras = ["d"], version = "^22.12.0"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
