name: update-requirements
on: [ push ]
jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          python -m pip install --upgrade pip
          pip install poetry
      - run: ./update-requirements.sh
        shell: bash
      - uses: EndBug/add-and-commit@v9.1.3
        with:
          message: "build(deps): Update requirements"
